#ifndef CC_MAP_GEN_H
#define CC_MAP_GEN_H
#include "ExtMath.h"
#include "Vectors.h"
CC_BEGIN_HEADER

/* Implements flatgrass map generator, and original classic vanilla map generation (with perlin noise)
   Based on: https://github.com/ClassiCube/ClassiCube/wiki/Minecraft-Classic-map-generation-algorithm
   Thanks to Jerralish for originally reverse engineering classic's algorithm, then preparing a high level overview of the algorithm.
   Copyright 2014-2025 ClassiCube | Licensed under BSD-3
*/

/* Progress between 0 and 1 for the current step */
extern volatile float Gen_CurrentProgress;
/* Name of the current step being performed */
extern volatile const char* Gen_CurrentState;
extern BlockRaw* Gen_Blocks;

struct MapGenerator {
	cc_bool (*Prepare)(int seed);
	void   (*Generate)(void);
	void   (*Setup)(void); /* Called after World_SetNewMap to configure environment, may be NULL */
};

extern const struct MapGenerator FlatgrassGen;
extern const struct MapGenerator NotchyGen;
extern const struct MapGenerator FloatingGen;
extern const struct MapGenerator CavesGen;
extern const struct MapGenerator EmptyGen;

/* Starts generating a map using the given generator */
void Gen_Start(STRING_REF const struct MapGenerator* gen, int seed,
				int width, int height, int length);
/* The currently active map generator (valid during and after generation) */
extern const struct MapGenerator* gen_active;
/* If Y >= 0, overrides the default spawn position after generation */
extern Vec3 Gen_SpawnOverride;

/* World theme applied during/after generation */
#define GEN_THEME_NORMAL   0
#define GEN_THEME_HELL     1
#define GEN_THEME_PARADISE 2
#define GEN_THEME_WOODS    3
#define GEN_THEME_DESERT   4
#define GEN_THEME_WINTER   5
#define GEN_THEME_COUNT    6
extern int Gen_Theme;
/* Checks whether the map generator has completed yet */
cc_bool Gen_IsDone(void);


extern BlockRaw* Tree_Blocks;
extern RNGState* Tree_Rnd;
/* Appropriate buffer size to hold positions and blocks generated by the tree generator. */
#define TREE_MAX_COUNT 96

/* Whether a tree can actually be generated at the given coordinates. */
cc_bool TreeGen_CanGrow(int treeX, int treeY, int treeZ, int treeHeight);
/* Generates the blocks (and their positions in the world) that actually make up a tree. */
/* Returns the number of blocks generated, which will be <= TREE_MAX_COUNT */
int  TreeGen_Grow(int treeX, int treeY, int treeZ, int height, IVec3* coords, BlockRaw* blocks);

CC_END_HEADER
#endif
